# Generated by Django 2.1.3 on 2018-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstokenlist',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
